apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: michiel.vryens@student.ucll.be
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx